package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstAssests generated by hbm2java
 */
@Entity
@Table(name = "mst_assests")
public class MstAssests implements java.io.Serializable {
private MstDepartment mstdepartment;
	private int assestsId;
	private Integer departmentId;
	private String assetsName;
	private Date createdOn;
	
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id",insertable=false,updatable=false)
	public MstDepartment getMstdepartment() {
		return mstdepartment;
	}

	public void setMstdepartment(MstDepartment mstdepartment) {
		this.mstdepartment = mstdepartment;
	}

	private String createdBy;

	public MstAssests() {
	}

	public MstAssests(int assestsId) {
		this.assestsId = assestsId;
	}

	public MstAssests(int assestsId, Integer departmentId, String assetsName, Date createdOn, String createdBy) {
		this.assestsId = assestsId;
		this.departmentId = departmentId;
		this.assetsName = assetsName;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "assests_id", unique = true, nullable = false)
	public int getAssestsId() {
		return this.assestsId;
	}

	public void setAssestsId(int assestsId) {
		this.assestsId = assestsId;
	}

	@Column(name = "department_id")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "assets_name", length = 500)
	public String getAssetsName() {
		return this.assetsName;
	}

	public void setAssetsName(String assetsName) {
		this.assetsName = assetsName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
