package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MstAnswers generated by hbm2java
 */
@Entity
@Table(name = "mst_answers")
public class MstAnswers implements java.io.Serializable {

	private Integer ansId;
	private MstQuestions mstQuestions;
	private String answer;
	private Set<TblFeedbacks> tblFeedbackses = new HashSet<TblFeedbacks>(0);

	public MstAnswers() {
	}

	public MstAnswers(MstQuestions mstQuestions, String answer, Set<TblFeedbacks> tblFeedbackses) {
		this.mstQuestions = mstQuestions;
		this.answer = answer;
		this.tblFeedbackses = tblFeedbackses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ans_id", unique = true, nullable = false)
	public Integer getAnsId() {
		return this.ansId;
	}

	public void setAnsId(Integer ansId) {
		this.ansId = ansId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ans_qid")
	public MstQuestions getMstQuestions() {
		return this.mstQuestions;
	}

	public void setMstQuestions(MstQuestions mstQuestions) {
		this.mstQuestions = mstQuestions;
	}

	@Column(name = "answer", length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstAnswers")
	public Set<TblFeedbacks> getTblFeedbackses() {
		return this.tblFeedbackses;
	}

	public void setTblFeedbackses(Set<TblFeedbacks> tblFeedbackses) {
		this.tblFeedbackses = tblFeedbackses;
	}

}
