package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MstPageAuthority generated by hbm2java
 */
@Entity
@Table(name = "mst_page_authority")
public class MstPageAuthority implements java.io.Serializable {

	private int authorityId;
	private MstWebpage mstWebpage;
	private Integer roleId;

	public MstPageAuthority() {
	}

	public MstPageAuthority(int authorityId) {
		this.authorityId = authorityId;
	}

	public MstPageAuthority(int authorityId, MstWebpage mstWebpage, Integer roleId) {
		this.authorityId = authorityId;
		this.mstWebpage = mstWebpage;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "authority_id", unique = true, nullable = false)
	public int getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(int authorityId) {
		this.authorityId = authorityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "page_id")
	public MstWebpage getMstWebpage() {
		return this.mstWebpage;
	}

	public void setMstWebpage(MstWebpage mstWebpage) {
		this.mstWebpage = mstWebpage;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
