package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstQuestions generated by hbm2java
 */
@Entity
@Table(name = "mst_questions")
public class MstQuestions implements java.io.Serializable {

	private Integer qid;
	private String questionText;
	private Integer roleId;
	private Boolean isActive;
	private String questionType;
	private Date createdOn;
	private String createdBy;
	private Integer stageId;
	private Set<MstAnswers> mstAnswerses = new HashSet<MstAnswers>(0);
	private Set<TblFeedbacks> tblFeedbackses = new HashSet<TblFeedbacks>(0);

	public MstQuestions() {
	}

	public MstQuestions(String questionText, Integer roleId, Boolean isActive, String questionType, Date createdOn,
			String createdBy, Integer stageId, Set mstAnswerses, Set tblFeedbackses) {
		this.questionText = questionText;
		this.roleId = roleId;
		this.isActive = isActive;
		this.questionType = questionType;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.stageId = stageId;
		this.mstAnswerses = mstAnswerses;
		this.tblFeedbackses = tblFeedbackses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Qid", unique = true, nullable = false)
	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	@Column(name = "question_text", length = 400)
	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "question_type", length = 50)
	public String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "stage_id")
	public Integer getStageId() {
		return this.stageId;
	}

	public void setStageId(Integer stageId) {
		this.stageId = stageId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstQuestions")
	public Set<MstAnswers> getMstAnswerses() {
		return this.mstAnswerses;
	}

	public void setMstAnswerses(Set<MstAnswers>  mstAnswerses) {
		this.mstAnswerses = mstAnswerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstQuestions")
	public Set<TblFeedbacks> getTblFeedbackses() {
		return this.tblFeedbackses;
	}

	public void setTblFeedbackses(Set<TblFeedbacks> tblFeedbackses) {
		this.tblFeedbackses = tblFeedbackses;
	}

}
