package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstReason generated by hbm2java
 */
@Entity
@Table(name = "mst_reason")
public class MstReason implements java.io.Serializable {

	private int reasonId;
	private String reason;
	private String createdBy;
	private Date createdOn;
	private Set<TblUserResignation> tblUserResignations = new HashSet<TblUserResignation>(0);

	public MstReason() {
	}

	public MstReason(int reasonId) {
		this.reasonId = reasonId;
	}

	public MstReason(int reasonId, String reason, String createdBy, Date createdOn, Set tblUserResignations) {
		this.reasonId = reasonId;
		this.reason = reason;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.tblUserResignations = tblUserResignations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reason_id", unique = true, nullable = false)
	public int getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(int reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "reason", length = 200)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstReason")
	public Set<TblUserResignation> getTblUserResignations() {
		return this.tblUserResignations;
	}

	public void setTblUserResignations(Set<TblUserResignation> tblUserResignations) {
		this.tblUserResignations = tblUserResignations;
	}

}
