package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstWebpage generated by hbm2java
 */
@Entity
@Table(name = "mst_webpage")
public class MstWebpage implements java.io.Serializable {

	private Integer pageId;
	private String pageName;
	private Boolean active;
	private Date createdOn;
	private String createdBy;
	private Set<MstPageAuthority> mstPageAuthorities = new HashSet<MstPageAuthority>(0);

	public MstWebpage() {
	}

	public MstWebpage(String pageName, Boolean active, Date createdOn, String createdBy, Set mstPageAuthorities) {
		this.pageName = pageName;
		this.active = active;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.mstPageAuthorities = mstPageAuthorities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "page_id", unique = true, nullable = false)
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "page_name", length = 60)
	public String getPageName() {
		return this.pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 6)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstWebpage")
	public Set<MstPageAuthority> getMstPageAuthorities() {
		return this.mstPageAuthorities;
	}

	public void setMstPageAuthorities(Set<MstPageAuthority> mstPageAuthorities) {
		this.mstPageAuthorities = mstPageAuthorities;
	}

}
