package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAssetsManagement generated by hbm2java
 */
@Entity
@Table(name = "tbl_assets_management")
public class TblAssetsManagement implements java.io.Serializable {

	private int assetsId;
	private TblUserResignation tblUserResignation;
	private Integer departmentId;
	private String assetsIssue;
	private String issuedBy;
	private Date issuedOn;
	private Date createdOn;
	private String createdBy;
	private String receivedBy;
	private Date receivedOn;
	private Integer itemStatus;
	private Set<TblNoDuesClearence> tblNoDuesClearences = new HashSet<TblNoDuesClearence>(0);

	public TblAssetsManagement() {
	}

	public TblAssetsManagement(int assetsId) {
		this.assetsId = assetsId;
	}

	public TblAssetsManagement(int assetsId, TblUserResignation tblUserResignation, Integer departmentId,
			String assetsIssue, String issuedBy, Date issuedOn, Date createdOn, String createdBy, String receivedBy,
			Date receivedOn, Integer itemStatus, Set tblNoDuesClearences) {
		this.assetsId = assetsId;
		this.tblUserResignation = tblUserResignation;
		this.departmentId = departmentId;
		this.assetsIssue = assetsIssue;
		this.issuedBy = issuedBy;
		this.issuedOn = issuedOn;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.receivedBy = receivedBy;
		this.receivedOn = receivedOn;
		this.itemStatus = itemStatus;
		this.tblNoDuesClearences = tblNoDuesClearences;
	}

	@Id

	@Column(name = "assets_id", unique = true, nullable = false)
	public int getAssetsId() {
		return this.assetsId;
	}

	public void setAssetsId(int assetsId) {
		this.assetsId = assetsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resignation_id")
	public TblUserResignation getTblUserResignation() {
		return this.tblUserResignation;
	}

	public void setTblUserResignation(TblUserResignation tblUserResignation) {
		this.tblUserResignation = tblUserResignation;
	}

	@Column(name = "department_id")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "assets_issue", length = 45)
	public String getAssetsIssue() {
		return this.assetsIssue;
	}

	public void setAssetsIssue(String assetsIssue) {
		this.assetsIssue = assetsIssue;
	}

	@Column(name = "issued_by", length = 15)
	public String getIssuedBy() {
		return this.issuedBy;
	}

	public void setIssuedBy(String issuedBy) {
		this.issuedBy = issuedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issued_on", length = 19)
	public Date getIssuedOn() {
		return this.issuedOn;
	}

	public void setIssuedOn(Date issuedOn) {
		this.issuedOn = issuedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "received_by", length = 15)
	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_on", length = 19)
	public Date getReceivedOn() {
		return this.receivedOn;
	}

	public void setReceivedOn(Date receivedOn) {
		this.receivedOn = receivedOn;
	}

	@Column(name = "item_status")
	public Integer getItemStatus() {
		return this.itemStatus;
	}

	public void setItemStatus(Integer itemStatus) {
		this.itemStatus = itemStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblAssetsManagement")
	public Set<TblNoDuesClearence> getTblNoDuesClearences() {
		return this.tblNoDuesClearences;
	}

	public void setTblNoDuesClearences(Set<TblNoDuesClearence> tblNoDuesClearences) {
		this.tblNoDuesClearences = tblNoDuesClearences;
	}

}
