package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblExEmpCommunication generated by hbm2java
 */
@Entity
@Table(name = "tbl_ex_emp_communication")
public class TblExEmpCommunication implements java.io.Serializable {

	private Integer communicationId;
	private TblExEmployeeQuery tblExEmployeeQuery;
	private String empCode;
	private Integer departrmentId;
	private Integer queryStatus;
	private Date createdOn;
	private String createdBy;
	private String queryReply;



	public TblExEmpCommunication() {
	}

	public TblExEmpCommunication(TblExEmployeeQuery tblExEmployeeQuery, String empCode, Integer departrmentId,
			Integer queryStatus, Date createdOn, String createdBy) {
		this.tblExEmployeeQuery = tblExEmployeeQuery;
		this.empCode = empCode;
		this.departrmentId = departrmentId;
		this.queryStatus = queryStatus;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "communication_id", unique = true, nullable = false)
	public Integer getCommunicationId() {
		return this.communicationId;
	}

	public void setCommunicationId(Integer communicationId) {
		this.communicationId = communicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "query_id")
	public TblExEmployeeQuery getTblExEmployeeQuery() {
		return this.tblExEmployeeQuery;
	}

	public void setTblExEmployeeQuery(TblExEmployeeQuery tblExEmployeeQuery) {
		this.tblExEmployeeQuery = tblExEmployeeQuery;
	}

	@Column(name = "emp_code", length = 15)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "departrment_id")
	public Integer getDepartrmentId() {
		return this.departrmentId;
	}

	public void setDepartrmentId(Integer departrmentId) {
		this.departrmentId = departrmentId;
	}
	
	@Column(name = "query_Reply")
	public String getQueryReply() {
		return queryReply;
	}

	public void setQueryReply(String queryReply) {
		this.queryReply = queryReply;
	}

	@Column(name = "query_status")
	public Integer getQueryStatus() {
		return this.queryStatus;
	}

	public void setQueryStatus(Integer queryStatus) {
		this.queryStatus = queryStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
