package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblExEmpCommunication generated by hbm2java
 */
@Entity
@Table(name = "tbl_ex_emp_communication")
public class TblExEmpCommunication implements java.io.Serializable {

	private Integer communicationId;
	private TblExEmployeeQuery tblExEmployeeQuery;
	private String queryFrom;
	private Date createdOn;
	private String queryText;



	public TblExEmpCommunication() {
	}

	public TblExEmpCommunication(TblExEmployeeQuery tblExEmployeeQuery, String queryFrom,Date createdOn) {
		this.tblExEmployeeQuery = tblExEmployeeQuery;
		this.queryFrom = queryFrom;
		this.createdOn = createdOn;
		
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "communication_id", unique = true, nullable = false)
	public Integer getCommunicationId() {
		return this.communicationId;
	}

	public void setCommunicationId(Integer communicationId) {
		this.communicationId = communicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "query_id")
	public TblExEmployeeQuery getTblExEmployeeQuery() {
		return this.tblExEmployeeQuery;
	}

	public void setTblExEmployeeQuery(TblExEmployeeQuery tblExEmployeeQuery) {
		this.tblExEmployeeQuery = tblExEmployeeQuery;
	}

	@Column(name = "query_From", length = 15)
	public String getQueryFrom() {
		return this.queryFrom;
	}

	public void setQueryFrom(String queryFrom) {
		this.queryFrom = queryFrom;
	}

	@Column(name = "query_text")
	public String getQueryText() {
		return queryText;
	}

	public void setQueryText(String queryText) {
		this.queryText = queryText;
	}
	


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}


}
