package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblNoDuesClearence generated by hbm2java
 */
@Entity
@Table(name = "tbl_no_dues_clearence")
public class TblNoDuesClearence implements java.io.Serializable {

	private Integer clearenceId;
	private TblUserResignation tbluserresignation;
	
	
	@ManyToOne(cascade=CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "resignation_id")
	public TblUserResignation getTbluserresignation() {
		return tbluserresignation;
	}

	public void setTbluserresignation(TblUserResignation tbluserresignation) {
		this.tbluserresignation = tbluserresignation;
	}

	/*private TblAssetsManagement tblAssetsManagement;*/
	private Integer departmentFinalStatus;
	private String comments;
	private Integer departmentId;

	@Column(name = "department_id")
	public Integer getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public TblNoDuesClearence() {
	}

	public TblNoDuesClearence( Integer departmentFinalStatus, String comments,TblUserResignation tbluserresignation) {/*TblAssetsManagement tblAssetsManagement,*/
		/*this.tblAssetsManagement = tblAssetsManagement;*/
		this.departmentFinalStatus = departmentFinalStatus;
		this.comments = comments;
		this.tbluserresignation=tbluserresignation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "clearence_id", unique = true, nullable = false)
	public Integer getClearenceId() {
		return this.clearenceId;
	}

	public void setClearenceId(Integer clearenceId) {
		this.clearenceId = clearenceId;
	}

	/*@ManyToOne(cascade=CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "resignation_id")
	public TblAssetsManagement getTblAssetsManagement() {
		return this.tblAssetsManagement;
	}*/

	/*public void setTblAssetsManagement(TblAssetsManagement tblAssetsManagement) {
		this.tblAssetsManagement = tblAssetsManagement;
	}
*/
	@Column(name = "department_final_status")
	public Integer getDepartmentFinalStatus() {
		return this.departmentFinalStatus;
	}

	public void setDepartmentFinalStatus(Integer departmentFinalStatus) {
		this.departmentFinalStatus = departmentFinalStatus;
	}

	@Column(name = "comments", length = 45)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
