package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TblUserResignation generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_resignation")
public class TblUserResignation implements java.io.Serializable {

	private Integer resignationId;
	private MstReason mstReason;
	private MstResignationStatus mstResignationStatus;
	private String empCode;
	private String comments;
	private Date resignationDate;
	private Date releivingDate;
	private String rmEmpcode;
	private String hrEmpcode;
	
	@Column(name="office_id")
	public String getOfficeId() {
		return officeId;
	}

	public void setOfficeId(String officeId) {
		this.officeId = officeId;
	}

	private int circleId;
	private String officeId;
	
	
	@Column(name="circle_id")
	public int getCircleId() {
		return circleId;
	}

	public void setCircleId(int circleId) {
		this.circleId = circleId;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "tbluserresignation")
	public Set<TblNoDuesClearence> getTblnoduesclearence() {
		return tblnoduesclearence;
	}

	public void setTblnoduesclearence(Set<TblNoDuesClearence> tblnoduesclearence) {
		this.tblnoduesclearence = tblnoduesclearence;
	}

	private String exEmpUserid;
	private String exEmpPassword;
	private String exEmpEmail;
	private Date rmApprovalDate;
	private Date hrApprovalDate;
	private Date hrLwdDate;
	private String approvedBy;
	private Set<TblNoDuesClearence> tblnoduesclearence=new HashSet<TblNoDuesClearence>(0);
	private Set<TblUploadedPath> tblUploadedPaths = new HashSet<TblUploadedPath>(0);
	private Set<TblFeedbacks> tblFeedbackses = new HashSet<TblFeedbacks>(0);
	private Set<TblAssetsManagement> tblAssetsManagements = new HashSet<TblAssetsManagement>(0);
	private Set<TblExEmployeeQuery> tblExEmployeeQueries = new HashSet<TblExEmployeeQuery>(0);

	public TblUserResignation() {
	}

	public TblUserResignation(String comments) {
		this.comments = comments;
	}

	public TblUserResignation(MstReason mstReason, MstResignationStatus mstResignationStatus, String empCode,
			String comments, Date resignationDate, Date releivingDate, String rmEmpcode, String hrEmpcode,
			String exEmpUserid, String exEmpPassword, String exEmpEmail, Date rmApprovalDate, Date hrApprovalDate,
			Date hrLwdDate, Set tblUploadedPaths, Set tblFeedbackses, Set tblAssetsManagements,
			Set tblExEmployeeQueries,Set tblnoduesclearence) {
		this.mstReason = mstReason;
		this.mstResignationStatus = mstResignationStatus;
		this.empCode = empCode;
		this.comments = comments;
		this.resignationDate = resignationDate;
		this.releivingDate = releivingDate;
		this.rmEmpcode = rmEmpcode;
		this.hrEmpcode = hrEmpcode;
		this.exEmpUserid = exEmpUserid;
		this.exEmpPassword = exEmpPassword;
		this.exEmpEmail = exEmpEmail;
		this.rmApprovalDate = rmApprovalDate;
		this.hrApprovalDate = hrApprovalDate;
		this.hrLwdDate = hrLwdDate;
		this.tblUploadedPaths = tblUploadedPaths;
		this.tblFeedbackses = tblFeedbackses;
		this.tblAssetsManagements = tblAssetsManagements;
		this.tblExEmployeeQueries = tblExEmployeeQueries;
		this.tblnoduesclearence=tblnoduesclearence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "resignation_id", unique = true, nullable = false)
	public Integer getResignationId() {
		return this.resignationId;
	}

	public void setResignationId(Integer resignationId) {
		this.resignationId = resignationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "leaving_reason")
	public MstReason getMstReason() {
		return this.mstReason;
	}

	public void setMstReason(MstReason mstReason) {
		this.mstReason = mstReason;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public MstResignationStatus getMstResignationStatus() {
		return this.mstResignationStatus;
	}

	public void setMstResignationStatus(MstResignationStatus mstResignationStatus) {
		this.mstResignationStatus = mstResignationStatus;
	}

	@Column(name = "emp_code", length = 15)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "comments", nullable = false, length = 450)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resignation_date", length = 19)
	public Date getResignationDate() {
		return this.resignationDate;
	}

	public void setResignationDate(Date resignationDate) {
		this.resignationDate = resignationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "releiving_date", length = 19)
	public Date getReleivingDate() {
		return this.releivingDate;
	}

	public void setReleivingDate(Date releivingDate) {
		this.releivingDate = releivingDate;
	}

	@Column(name = "rm_empcode", length = 15)
	public String getRmEmpcode() {
		return this.rmEmpcode;
	}

	public void setRmEmpcode(String rmEmpcode) {
		this.rmEmpcode = rmEmpcode;
	}

	@Column(name = "hr_empcode", length = 15)
	public String getHrEmpcode() {
		return this.hrEmpcode;
	}

	public void setHrEmpcode(String hrEmpcode) {
		this.hrEmpcode = hrEmpcode;
	}

	@Column(name = "ex_emp_userid", length = 15)
	public String getExEmpUserid() {
		return this.exEmpUserid;
	}

	public void setExEmpUserid(String exEmpUserid) {
		this.exEmpUserid = exEmpUserid;
	}

	@Column(name = "ex_emp_password", length = 15)
	public String getExEmpPassword() {
		return this.exEmpPassword;
	}

	public void setExEmpPassword(String exEmpPassword) {
		this.exEmpPassword = exEmpPassword;
	}

	@Column(name = "ex_emp_email", length = 50)
	public String getExEmpEmail() {
		return this.exEmpEmail;
	}

	public void setExEmpEmail(String exEmpEmail) {
		this.exEmpEmail = exEmpEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rm_approval_date", length = 19)
	public Date getRmApprovalDate() {
		return this.rmApprovalDate;
	}

	public void setRmApprovalDate(Date rmApprovalDate) {
		this.rmApprovalDate = rmApprovalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hr_approval_date", length = 19)
	public Date getHrApprovalDate() {
		return this.hrApprovalDate;
	}

	public void setHrApprovalDate(Date hrApprovalDate) {
		this.hrApprovalDate = hrApprovalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hr_lwd_date", length = 19)
	public Date getHrLwdDate() {
		return this.hrLwdDate;
	}

	public void setHrLwdDate(Date hrLwdDate) {
		this.hrLwdDate = hrLwdDate;
	}

	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "tblUserResignation")
	public Set<TblUploadedPath> getTblUploadedPaths() {
		return this.tblUploadedPaths;
	}

	public void setTblUploadedPaths(Set<TblUploadedPath> tblUploadedPaths) {
		this.tblUploadedPaths = tblUploadedPaths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserResignation")
	public Set<TblFeedbacks> getTblFeedbackses() {
		return this.tblFeedbackses;
	}

	public void setTblFeedbackses(Set<TblFeedbacks> tblFeedbackses) {
		this.tblFeedbackses = tblFeedbackses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserResignation")
	public Set<TblAssetsManagement> getTblAssetsManagements() {
		return this.tblAssetsManagements;
	}

	public void setTblAssetsManagements(Set<TblAssetsManagement> tblAssetsManagements) {
		this.tblAssetsManagements = tblAssetsManagements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserResignation")
	public Set<TblExEmployeeQuery> getTblExEmployeeQueries() {
		return this.tblExEmployeeQueries;
	}

	public void setTblExEmployeeQueries(Set<TblExEmployeeQuery> tblExEmployeeQueries) {
		this.tblExEmployeeQueries = tblExEmployeeQueries;
	}

	@Column(name="approvedby",length=15)
	public String getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	}
