package com.softage.hrms.model;
// Generated Dec 6, 2016 10:45:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUploadedPath generated by hbm2java
 */
@Entity
@Table(name = "tbl_uploaded_path")
public class TblUploadedPath implements java.io.Serializable {

	private Integer pathId;
	private MstUploadItem mstUploadItem;
	private TblUserResignation tblUserResignation;
	private String path;
	private String empCode;
	private Date uploadedOn;
	private String uploadedBy;
	private Date downloadOn;
	private String downloadBy;

	public TblUploadedPath() {
	}

	public TblUploadedPath(MstUploadItem mstUploadItem, TblUserResignation tblUserResignation, String path,
			String empCode, Date uploadedOn, String uploadedBy, Date downloadOn, String downloadBy) {
		this.mstUploadItem = mstUploadItem;
		this.tblUserResignation = tblUserResignation;
		this.path = path;
		this.empCode = empCode;
		this.uploadedOn = uploadedOn;
		this.uploadedBy = uploadedBy;
		this.downloadOn = downloadOn;
		this.downloadBy = downloadBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "path_id", unique = true, nullable = false)
	public Integer getPathId() {
		return this.pathId;
	}

	public void setPathId(Integer pathId) {
		this.pathId = pathId;
	}

	@ManyToOne(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public MstUploadItem getMstUploadItem() {
		return this.mstUploadItem;
	}

	public void setMstUploadItem(MstUploadItem mstUploadItem) {
		this.mstUploadItem = mstUploadItem;
	}

	@ManyToOne(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "resign_id")
	public TblUserResignation getTblUserResignation() {
		return this.tblUserResignation;
	}

	public void setTblUserResignation(TblUserResignation tblUserResignation) {
		this.tblUserResignation = tblUserResignation;
	}

	@Column(name = "path", length = 2000)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "emp_code", length = 15)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uploaded_on", length = 19)
	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	@Column(name = "uploaded_by", length = 15)
	public String getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(String uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "download_on", length = 19)
	public Date getDownloadOn() {
		return this.downloadOn;
	}

	public void setDownloadOn(Date downloadOn) {
		this.downloadOn = downloadOn;
	}

	@Column(name = "download_by", length = 15)
	public String getDownloadBy() {
		return this.downloadBy;
	}

	public void setDownloadBy(String downloadBy) {
		this.downloadBy = downloadBy;
	}

}
